# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yashprit Blog
tagline:             'Sharing what I have learned along the way'
description:         'Hi. I am Yashprit Singh.I do things and sometimes write about it here. I am a Software Engineer from India.'
url:                 http://yashprit.com
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Yashprit Singh
  url:               https://twitter.com/yashprit
  email:             yashprit@gmail.com

# Custom vars
version:             1.0.0
